name: '' # set whatever name you want to your github job
on: 
  push:
    branches:
      - heroku # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: 'backend' # set the path to the folder where the Dockerfile is located
          options: '-e MONGO_URI=${{ secrets.MONGO_URI }} -e PORT=${{secrets.PORT}} -e SECRET=${{secrets.SECRET}}' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web